### ISSUE TITLE
Improve "getting started section"

### ISSUE THREAD

**Issue by tychota** [lightvector/GoNN#4]
I think we can improve the readme by adding a better getting started section.

The following section points are not straightforward

* installing hdf5: maybe we can add apt-get or brew command to install on unix
* building: it should be better with #3 and CMake
* downloading sgf: where should I go ? (I used https://u-go.net/gamerecords/ but add to change https://github.com/lightvector/GoNN/blob/master/writedata/write.cpp#L291-L296)
* extracting training file: we could add a demo command to run, like:
  * `write  -target "nextmove" -max-handicap 4 -min-opp-rank 0 -min-rank 0 -keep-test-prob 0.3 -test-game-prob 0.3 -train-shards 4  -pool-size 100 -output 4d.h5 -gamesdir ./kgs`
  * explain the parameters a bit more
* training:
  * how to install the requirements (either `requirements.txt` or `Pipfile` https://github.com/pypa/pipenv, my preference but require to `pip install pipenv` first)
  * what are the default parameters (epoch, batch size) of the training
  * if I have a tensorflow without a 1080, how can I reduce the size of my data set / epoch, to have faster results appearing in the console (when I test, I first want to see some result, even if they are worst than perfect epoch before letting my PC train for hours without feedbacks)
  * how can I use tensorboard to have some feedbacks (require some modifications of train.py as it have no `tf.summary` or `FileWriter`)

What do you think ?
I think this can improve the first usage by a lot and I can contribute if you want ?

**Comment by lightvector** [comment]
Thanks for your interest! :)

Yeah, you identified some various things are hardcoded in ways that aren't ideal and could be improved. Keep in mind that this is still just my own personal sandbox for experimentation, rather than a library or codebase I intended for widespread use. As I work on and add new things over time, unfortunately I don't plan to spend much time making sure it continues to work across different setups other than my own.

I also still expect to continue occasionally hardcoding details that are specific to my own use case in the future. The lines https://github.com/lightvector/GoNN/blob/master/writedata/write.cpp#L291-L296 you identified are definitely an example of that. Actually, in a bunch of commits that I haven't pushed to Github yet, I added a lot more to that part of the code and nearby sections to apply specific different filtering conditions varying by dataset, in order to try to clean the quirks of each of four datasets for the particular purpose I'm going to be using the data and the resulting neural net for. These filter conditions wouldn't necessarily be desirable or generalize to someone else's use case, so that part has actually gotten a lot "worse"...

Despite all that, if you think there are small and simple changes that don't require ongoing maintenance, or additional pointers that could be added to the readme to make it easier for someone to get it working on their own (in the worst case, perhaps just pointing out what hardcoded sections someone might need to modify for themselves), I'm happy to consider and accept contributions. At this point, what are your thoughts?

**Comment by lightvector** [comment]
I merged #3 and pushed a stack of commits that should address some of these issues. 
* ae92e77 - Ignore compiled write executable 
* b1f2f7b - Improve readme for getting started 
* 2dc4892 - Rearrange write.cpp a bit
* f90ba9e - Fix cmake file for older versions 
* cf22f05 - Add some more comments 
* 4f911e9 - Make a bunch of writedata flags optional, be more rigorous about test/validation terminology

**Comment by tychota** [comment]
Thank you very much. Will try this weekend.

**Comment by tychota** [comment]
The readme is not so much clearer, I will close this issue.
Thanks again :)
