### ISSUE TITLE
potential sgfmill speedup

### ISSUE THREAD

**Issue by sethtroisi** [lightvector/GoNN#5]
I see you forked sgfmill into your project. You might want to take a look at https://github.com/mattheww/sgfmill/pull/2 it was a big speedup (~10x) for me.

**Comment by lightvector** [comment]
I actually have my own board class in python, since it was necessary in order to implement things like fast ladder search, so I think I'm not using that part of sgfmill. I'm using sgfmill only for the SGF parsing (unless the building of the SGF tree also tries to play the moves on a board for some reason).

But thanks for the tip!
