### ISSUE TITLE
about efficient multithreaded MCTS implementation

### ISSUE THREAD

**Issue by 51616** [lightvector/GoNN#7]
I am very curious about this implementation and I guess it has to be done in low-level (c++ ?) which i have no idea how to since i mainly use python for my project and its default multiprocessing library is very inefficient for this task. 

Where can i read the implementation details? Is there a specific part of this repo i should look into?

**Comment by lightvector** [comment]
The implementation has two parts.
https://github.com/lightvector/KataGo/blob/master/cpp/neuralnet/nneval.h
Here and in the associated .cpp file, we have an `NNEvaluator` implementing threadsafe neural net evaluation batching. The contract is roughly that initialized and threads are spawned, any number of clients may concurrently call `evaluate` on any board positions, and it will take care of batching requests, running them on the GPU, and ensuring each client gets the appropriate result.

https://github.com/lightvector/KataGo/blob/master/cpp/search/search.h
The multithreaded MCTS is then implemented here and in the associated .cpp file, implementing the synchronization throughout the search tree and making use of the fact that `NNEvaluator::evaluate` is threadsafe.

I would say my implementation is reasonable, but not necessarily super-efficient. Someone more experienced than me about performance optimization could probably improve it, particularly if the goal is making best use of a GPU for a single multithreaded search, rather than overall throughput. A big reason for this two-part design is that _the same NNEvaluator can be shared between multiple simultaneous searches!_ The self-play code makes heavy use of this, _spawning hundreds of simultaneous games per GPU in the same process_, making extremely efficient use of the GPU by allowing very large batch sizes. That was the main focus, and the fact that the design still works pretty well for a single multithreaded search for just a single game is a bonus.

**Comment by 51616** [comment]
@lightvector Thanks a lot for the reply and detailed explanation!
